---
title: "Shared Options"
---

## Which dataset to use?

This tool retrieves information stored in a [SQLite3](https://sqlite.org/index.html) database, which is preprocessed by Bayesian mixture modeling from single-cell transcriptomics data.

Multiple datasets could co-exist in the database, and this switch allows users to explore what intrigues them the most.

#### Which genes to consider?

By default, every gene that is detected in the dataset is used for analysis and visualization. You can provide your own gene list to focus on them. Please note that gene symbols used in reference genomes could change over time, and you **need to examine if your provided gene list utilize the same naming scheme as your data**.

#### Clusters of interest

The clusters to focus on (Find distinct genes within) or to highlight (Plot expression trend).

#### Probability threshold to be considered as expressed

Binomial probability of a gene being expressed in a cluster/cell type . A cutoff is selected here to decide the probability threshold to consider a gene **ON**.

### From cluster

Starting from one cluster, define how consistent among different stages/ conditions you desire for a marker. After clicking **Show genes**, the consistently expressing genes would be demonstrated and ranked by how many other clusters they are also detected in.

You can select a gene, and move forward to **Find distinct genes within**.

### From gene

Similar to **From clustser**, but starting from a gene. You define how consistent among different stages/conditions you desire for a marker. After clicking **Show clusters**, all clusters that consistently express this gene would be shown, and you can choose the clusters that you want to distinguish and move forward to **Find distinct genes within**. other clusters they are also detected in.

### Find distinct genes within

Among your clusters of interest, find genes that are only **ON** in one cluster but not others. Use the slide bar to define **ON** as *expressed in at least N stages*. Alternatively, use the check boxes to select the stages a gene must be expressed to be considered as **ON**.

Click **Find genes** to visualize how well you can distinguish these clusters with the addition of another gene. You could pick a gene from this list to use together with what you chose in **From cluster** or **From gene**.

You might want to visualize this gene pair to see how they express in other clusters in the dataset with **Co-expression plot**.

### Co-expression plot

Select genes that you are interested in, and visualize their co-expression pattern through different stages.

### Plot expression trend

This tool generates an interactive line plot of log-transformed cluster average normalized expression. Cluster label will be shown when you point your cursor to a point. Clusters of interest will be highlighted (and coded with distinct colors when you download a static version of the plot).
