---
title: "Quick Start"
---

`scMarko` aims to help with the heuristic selection of markers for your cell
types of interest by:

## Recommended Workflow

```{mermaid}
flowchart TB
  A[From cluster]--Select 1st consistent marker\nand other clusters markerd by it--> C[Find distinct genes within]
  B[From gene]--Use it as the 1st marker\nand find all clusters consistently marked by it--> C
  C--Find genes that mark only one\ncluster among the above ones--> D[Co-expression plot]
  D--Select the 2nd marker and\nsee the expression of the marker combo\nin the whole dataset--> E[Plot expression trend]
```


## Select your first marker

Depends on the prior knowledge about the diversity in your tissue of interest,
you might start from a cell type (**From cluster**) and select a gene that marks
it. `scMarko` will provide a list of other clusters (*offtargets*) that the
second marker in the combination aims to distinguish.

Sometimes, you are interested in cell types that are marked by the same gene,
and that gene will be your first marker. `scMarko` will list all clusters that
are likely to express this gene so you can find putative second markers that
will further tell them apart (**From gene**).

## Select a second marker

**Find distinct genes** lists the genes that are expressed in only one of the
clusters from **From cluster** or **From gene**. We hope the clusters that
you are interested in have at least one such gene. If not, you could select the
clusters that co-express your first two markers, and run **Find distinct genes**
on them to find a third marker that distinguish them.

## Inspect your marker combo

While the marker combinations selected by this process should be specific among
the dataset, there could be gray zones during the binarization process. To see
if this is the case, plotting normalized expression value and see how your
clusters of interest compare to others on this scale could provide some insight.

**Plot expression trend** plots normalized expression values as a line plot 
across stages/conditions and highlights the cluster you selected.

To inspect how your marker combinations look like in your dataset (e.g., which
clusters expresses either of them at a stage/condition), **Co-expression plot**
plots this information for your combinations of markers.
